# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
    include:
    - main
 paths:
    include:
      - src/libraries


pool:
  vmImage: 'ubuntu'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
   
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      
- task: DotNetCoreCLI@2
  inputs:
      command: 'build'
      projects: '**/*.csproj'
      
- task: DotNetCoreCLI@2
  inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'byBuildNumber'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f9a3ba6c-3ffc-42f5-9f8a-30e9c233099f'
